[build]
  command = "npm run scrape"
  publish = "public"

[functions]
  directory = "netlify/functions"
  included_files = ["public/**"]

[[scheduled.functions]]
  name = "live-cron"
  schedule = "0 3 * * *"